# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 27 Nov 2022 13:24:57 +0000
*               @ALL          0
*               @user         8
