# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Sun, 27 Nov 2022 13:24:57 +0000
*	@ALL	0
*	@contributors	2
*	@user	1
meta:*	@contributors	0
meta:*	@user	0
playground:*	@ALL	0
wiki:*	@user	0
media:*	@contributors	8
