<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: vatssa1
 * Date: Sun, 27 Nov 2022 20:21:50 +0000
 */

$conf['title'] = 'VATSSA eAIP';
$conf['template'] = 'sprintdoc';
$conf['license'] = 'cc-by-sa';
$conf['allowdebug'] = 1;
$conf['useacl'] = 1;
$conf['authtype'] = 'oauth';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register,resendpwd,profile';
$conf['userewrite'] = '1';
$conf['useslash'] = 1;
$conf['plugin']['discussion']['automatic'] = 1;
$conf['plugin']['oauth']['register-on-auth'] = 1;
$conf['plugin']['oauthgeneric']['key'] = '1180';
$conf['plugin']['oauthgeneric']['secret'] = 'c1EikhnxndXrW6w0DlRaF6I3jAL4lwcwQ5euc1yK';
$conf['plugin']['oauthgeneric']['authurl'] = 'https://auth.vatsim.net/oauth/authorize';
$conf['plugin']['oauthgeneric']['tokenurl'] = 'https://auth.vatsim.net/oauth/token';
$conf['plugin']['oauthgeneric']['userurl'] = 'https://auth.vatsim.net/api/user';
$conf['plugin']['oauthgeneric']['authmethod'] = '1';
$conf['plugin']['oauthgeneric']['scopes'] = array('email', 'full_name', 'vatsim_details');
$conf['plugin']['oauthgeneric']['json-user'] = 'data.cid';
$conf['plugin']['oauthgeneric']['json-name'] = 'data.personal.name_full';
$conf['plugin']['oauthgeneric']['json-mail'] = 'data.personal.email';
$conf['plugin']['tabinclude']['toc_in_tab'] = 1;
