# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sun, 27 Nov 2022 13:24:57 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

vatssa1:$2y$10$z2DSPAHYpiT9dneoewuKuetQ6yqL0D3sUQI5ZVrgmBihRXOxDjzi.:Miguel Albano:vatssa1@vatssa.com:admin,user
810471:$2y$10$Rdvuz5mCI4jq4bcjeXFsiu9XHCP8o8HFRvGy2HdDzJ3AzV3GXnmCG:Miguel Albano:hello@vcaptainmike.com:admin,user
